### ISSUE TITLE
Failed to load system roots

### ISSUE THREAD

**Issue by bwagner5** [dump247/ec2metaproxy#4]
I cannot get the security-credentials in my container. When I check `docker logs ec2metaproxy` the error is recorded as: 

`caused by: Post https://sts.amazonaws.com/: x509: failed to load system roots and no roots provided`

it seems ca-certificates aren't installed/configured correctly in the image?

**Comment by dump247** [comment]
Thanks for the report. A new dump247/ec2metaproxy image has been built and pushed that resolves the issue.

For reference, the issue was resolved in #300adc1f62e921cef6e036c9b01d5dcc4a929dca.
