### ISSUE TITLE
Why is the role set via an environment variable?

### ISSUE THREAD

**Issue by dr-impossible** [dump247/ec2metaproxy#7]
I'm concerned that the role for a container is set by an environment variable. It's possible for the guest container to change the value of `IAM_ROLE` at any time, so wouldn't this give the guest container access to assume any role that the Docker host has access to? It sounds to me like this doesn't provide much advantage over a single role for the host with access to everything.

I think that it would be better if the setting for IAM_ROLE were stored in a place that is read-only for the guest container. The docker documentation wasn't clear on whether a container could modify its own labels, but would that be a better place to store this setting?

**Comment by dump247** [comment]
I believe you may be misunderstanding how this works. The role is stored in the environment variables configuration for the container, but only as a convenient place to retrieve metadata. The container environment variables can only be set when the container is created, but can't be modified while running. The role value is retrieved with the docker API by querying the container configuration and not by examining the environment of the processes running in the container.

Even if what you say were true, there would still be significant value in limiting what each container can do by default, rather then giving all permissions to all containers by default.

Labels would achieve the same result. Labels are a more recent feature.

Regardless, you should not treat this service as a complete security solution. If a process can escape the container, it can then assume any role the host system can.

**Comment by dr-impossible** [comment]
That clears it up. I was just thrown off by the fact that it was an environment variable. It implied that the app running in the container would somehow pass that value back to the service
